# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chat.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'chat.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\x12\x04\x63hat\x1a\x1fgoogle/protobuf/timestamp.proto\" \n\x04User\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"o\n\x07Message\x12\x10\n\x08senderId\x18\x01 \x01(\t\x12\x12\n\nreceiverId\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12-\n\ttimestamp\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"3\n\x07\x43onnect\x12\x18\n\x04user\x18\x01 \x01(\x0b\x32\n.chat.User\x12\x0e\n\x06\x61\x63tive\x18\x02 \x01(\x08\"\x07\n\x05\x43lose2\x98\x01\n\x0b\x43hatService\x12.\n\x0c\x43reateStream\x12\r.chat.Connect\x1a\r.chat.Message0\x01\x12)\n\x0bSendMessage\x12\r.chat.Message\x1a\x0b.chat.Close\x12.\n\x10\x42roadcastMessage\x12\r.chat.Message\x1a\x0b.chat.CloseB\x15Z\x13\x65xample/gochat/chatb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\023example/gochat/chat'
  _globals['_USER']._serialized_start=53
  _globals['_USER']._serialized_end=85
  _globals['_MESSAGE']._serialized_start=87
  _globals['_MESSAGE']._serialized_end=198
  _globals['_CONNECT']._serialized_start=200
  _globals['_CONNECT']._serialized_end=251
  _globals['_CLOSE']._serialized_start=253
  _globals['_CLOSE']._serialized_end=260
  _globals['_CHATSERVICE']._serialized_start=263
  _globals['_CHATSERVICE']._serialized_end=415
# @@protoc_insertion_point(module_scope)
